name: Question or Discussion
description: Ask a question or start a discussion
title: "[Question]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Have a question about hfortix? Ask away! For general Fortinet questions, please use the Fortinet community forums.
  
  - type: textarea
    id: question
    attributes:
      label: Question
      description: What would you like to know?
      placeholder: How do I...?
    validations:
      required: true
  
  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What is your question about?
      options:
        - Installation and Setup
        - Usage and API
        - FortiOS Integration
        - FortiManager Integration
        - FortiAnalyzer Integration
        - Authentication
        - Error Handling
        - Best Practices
        - Other
    validations:
      required: true
  
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Provide any additional context that might be helpful
      placeholder: I'm trying to accomplish...
  
  - type: textarea
    id: code
    attributes:
      label: Code Sample (if applicable)
      description: Share any relevant code snippets
      render: python
